api/urls.py
from django.urls import path
from .views import *

app_name = 'api'


urlpatterns = [
    path('profile/create/', NewUserProfileApi.as_view(), name='create_profile')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('', include('profile_site.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_site/urls.py
from django.urls import path
from .views import profile, edit, register_user, index


app_name = 'profile'


urlpatterns = [
    path('register/', register_user, name='register'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit, name='edit'),
    path('', index, name='index'),
]

api/models.py
from django.db import models

# Create your models here.

profile_site/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ProfileUser(AbstractUser):
    patronymic = models.CharField(max_length=25, blank=True,  verbose_name='Отчество')
    phone_number = models.CharField(max_length=12, blank=True, verbose_name='Номер телефона', default='0312000000')
    address = models.CharField(max_length=100, blank=True, verbose_name='Адрес')
    inn = models.CharField(max_length=14, blank=True, verbose_name='ИНН', default='000000000000')

    def __str__(self):
        return f'Профиль пользователя {self.username}'

    class Meta(AbstractUser.Meta):
        verbose_name = 'Ползователь'
        verbose_name_plural = 'Пользователи'

profile_site/forms.py
from django import forms
from .models import ProfileUser


class ProfileUserChangeForm(forms.ModelForm):
    class Meta:
        model = ProfileUser
        fields = ('username', 'first_name', 'last_name', 'patronymic', 'email', 'phone_number', 'address', 'inn')


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(min_length=8, max_length=20, label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(min_length=8, max_length=20, label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = ProfileUser
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cd['password2']

api/views.py
from django.shortcuts import render
from rest_framework import generics
from api.serializers import ProfileCreateSerializer


class NewUserProfileApi(generics.CreateAPIView):
    serializer_class = ProfileCreateSerializer

profile_site/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


from .forms import ProfileUserChangeForm, UserRegisterForm


def index(request):
    return render(request, 'main/index.html')


@login_required
def profile(request):
    return render(request, 'profile/profile.html')


def edit(request):
    if request.method == 'POST':
        user_form = ProfileUserChangeForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
        return redirect('profile:profile')
    else:
        user_form = ProfileUserChangeForm(instance=request.user)
    return render(request, 'profile/edit.html', {'user_form': user_form})


def register_user(request):
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegisterForm()
    return render(request, 'registration/register.html', {'user_form': user_form})

profile_site/templates/main/index.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% bootstrap_css %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <a class="btn btn-primary" href="{% url 'admin:index' %}" role="button">Админка</a>
        <a class="btn btn-primary" href="{% url 'login' %}" role="button">Войти</a>
        <a class="btn btn-primary" href="{% url 'profile:register' %}" role="button">Регистрация</a>
        <a class="btn btn-primary" href="{% url 'profile:profile' %}" role="button">Профиль</a>
        <a class="btn btn-primary" href="{% url 'api:create_profile' %}" role="button">Апишка</a>
    </div>
    <div class="container-fluid">
        <p><a class="btn btn-primary" href="https://github.com/pipkamv" role="button">GitHub - Канай</a><br></p>
        <p><a class="btn btn-primary" href="https://github.com/Akylbek005" role="button">GitGub - Акылбек</a><br></p>
        <p><a class="btn btn-primary" href="https://github.com/jumagylov" role="button">GitHub - Актилек</a><br></p>
    </div>

</body>
</html>

profile_site/templates/profile/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <h1>Edit your account</h1>
    <p>You can edit your account using the following form:</p>
    <form action="." method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
</body>
</html>

profile_site/templates/profile/profile.html
{%load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль пользователя</title>
</head>
<body>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <h1>Ваш профиль {{ user.username }}</h1>
    <table>
        <tr><td>Имя:</td>               <td></td><td>{{ user.first_name }}</td></tr>
        <tr><td>Фамилия:</td>           <td></td><td>{{ user.last_name }}</td></tr>
        <tr><td>Отчество:</td>          <td></td><td>{{ user.patronymic }}</td></tr>
        <tr><td>Емайл:</td>             <td></td><td>{{ user.email }}</td></tr>
        <tr><td>Номер телефона:</td>    <td></td><td>{{ user.phone_number }}</td></tr>
        <tr><td>Адрес:</td>             <td></td><td>{{ user.address }}</td></tr>
        <tr><td>ИНН:</td>               <td></td><td>{{ user.inn }}</td></tr>
    </table>
    <a href="{% url 'profile:edit' %}">Редактировать профиль</a><br>
    <a href="{% url 'logout' %}">Выйти</a><br>
    <a href="{% url 'admin:index'%}">Админ</a>
</body>
</html>